--- FUNCTION SOURCE (/home/javad/sources/v8/v8/test/mjsunit/regress/regress-3252443.js:x) id{0,-1} start{1699} ---
(p0, p1, p2, p3) {
  document.getElementById(p1+p0).style.display='';
  document.getElementById(p1+''+p0).style.backgroundColor = "";
  document.getElementById(p1+''+p0).style.color="";
  document.getElementById(p1+''+p0).style.borderBottomColor = "";
  for (var i = p3; i <= p2; ++i) {
    if (i != p0) {
      document.getElementById(p1+i).style.display='';
      document.getElementById(p1+''+i).style.backgroundColor = "";
      document.getElementById(p1+''+i).style.color="";
      document.getElementById(p1+''+i).style.borderBottomColor = "";
    }
  }
}
--- END ---
--- FUNCTION SOURCE (/home/javad/sources/v8/v8/test/mjsunit/regress/regress-3252443.js:document.getElementById) id{0,0} start{1661} ---
(s) { return { style: {}}}
--- END ---
INLINE (document.getElementById) id{0,0} AS 0 AT <-1:1699>
--- FUNCTION SOURCE (/home/javad/sources/v8/v8/test/mjsunit/regress/regress-3252443.js:document.getElementById) id{0,0} start{1661} ---
(s) { return { style: {}}}
--- END ---
INLINE (document.getElementById) id{0,0} AS 1 AT <-1:1699>
--- FUNCTION SOURCE (/home/javad/sources/v8/v8/test/mjsunit/regress/regress-3252443.js:document.getElementById) id{0,0} start{1661} ---
(s) { return { style: {}}}
--- END ---
INLINE (document.getElementById) id{0,0} AS 2 AT <-1:1699>
--- FUNCTION SOURCE (/home/javad/sources/v8/v8/test/mjsunit/regress/regress-3252443.js:document.getElementById) id{0,0} start{1661} ---
(s) { return { style: {}}}
--- END ---
INLINE (document.getElementById) id{0,0} AS 3 AT <-1:1699>
